### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by MJunaidAhmad** [samkitano/laravel-user-activation#1]
Need to use it with laravel 5.4 (haven't tested it yet with 5.4). It would be really helpful if you can add support for it or even if you will give me a little guidance, I will be more then happy to do it.

**Comment by samkitano** [comment]
Hi @MJunaidAhmad! It should work fine in 5.4

Have you tried yet? Are you getting any errors?

**Comment by MJunaidAhmad** [comment]
I tried it and everything was fine except the step 5. In laravel 5.4 they have removed the AuthController, so not sure what to do about step 5.

**Comment by samkitano** [comment]
I'm deeply sorry for the long time taken to reply, @MJunaidAhmad! I was on vacation with very limited access to the internet.

You are right. The AuthController was removed in 5.4, so this package will be kind of useless for the latest versions.

I'll write a new updated package as soon as I have some available time.

I hope you have found a suitable alternative for your project, since you opened this issue. Once again, I apologise for not being able to help you in due time.

Cheers

**Comment by samkitano** [comment]
just [released](https://github.com/samkitano/aktiv8me) a new improved version, for Laravel 1.4.*
